[package]
name = "solution"
version = "0.1.0"
authors = ["zLeoAlex <z.alex.leo@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.bench]
opt-level = 2
codegen-units = 1

[profile.test]
opt-level = 2
codegen-units = 1

[dependencies]
paste = "*"
